---
title: "Visualizing Data and Clustering Codes"
format: html
editor: visual
---

## Reading In the Data

```{r}
data = read.csv("/Users/labibawajihasiddiquei/Downloads/lung_cancer_data.csv")

library(titanic)
library(dplyr)
library(janitor)
library(ggplot2)
library(tidyr)
```

## Cleaning

**Read the book and see if you do anything else**

```{r}
data = clean_names(data)

#names(data) ### changed the names from upper case to lower case 

#str(data) # data.frame':	23658 obs. of  38 variables:

data = na.omit(data) 
#str(data) ## 'data.frame':	23658 obs. of  38 variables:

## there are no missig data points 

get_dupes(data) ## no duplicates found either 
```

## Grouping

```{r}
checking_age = data %>%
  group_by(treatment) %>%
  summarise(med_age = median(age),
            mean_age = mean(age)) %>%
  mutate(differnece = med_age -  mean_age) 
  
checking_age
```

```{r}
  group_by(treatment) %>%  
  summarise(med_tumor_size_mm = median(tumor_size_mm),
            mean_tumor_size_mm = mean(tumor_size_mm)) %>%
  mutate(differnece = med_tumor_size_mm -  mean_tumor_size_mm)
```

## BoxPlots to Check For Outliers

```{r}
boxplot(data$age, data$tumor_size_mm, data$survival_months, 
        data$blood_pressure_systolic, 
        data$blood_pressure_diastolic,
        data$blood_pressure_pulse, 
        data$alkaline_phosphatase_level, 
        data$alanine_aminotransferase_level, 
        data$aspartate_aminotransferase_level, 
        data$ldh_level, 
        data$glucose_level, 
        data$smoking_pack_years,
        names = c("Age", "Tumor Size", "Survival Months", "BP Systolic", "BP Diastolic", 
                  "BP Pulse", "Alkaline Phosphatase", "Alanine Aminotransferase", 
                  "Aspartate Aminotransferase", "LDH Level", "Glucose Level", 
                  "Smoking Pack Years"),
        main = "Boxplot: Checking for Outliers", 
        ylab='Scale',
        las = 2 # Rotate x-axis labels for better readability
        )
```

```{r}
boxplot(data$performance_status, 
        data$hemoglobin_level, 
        data$white_blood_cell_count, 
        data$albumin_level, 
        data$creatinine_level,
        data$calcium_level, 
        data$phosphorus_level,
        data$potassium_level, 
        main = "Boxplot: Checking for Outliers", 
        names = c("Performace Status", "Hemoglobin Level", " White Blood Cell Count", 
                  "Albumin Level", "Creatinine Level", "Calcium Level", 
                  "Phosphorus Level", 
                  "Potassium Level"),
        ylab = "Scale", 
        las = 2)
```

```{r}
boxplot(data$platelet_count, main = "Boxplot: Checking for Outliers",
       ylab='Scale', xlab='Platelet Count')
```

```{r}
boxplot(data$sodium_level,  main = "Boxplot: Checking for Outliers",
        ylab='Scale', xlab='Sodium Level')
```

## BarPlots to Look at the Distribution

```{r}
ggplot(data, aes(x = treatment, fill = treatment)) +
  geom_bar() +
  labs(title = "Counts of Patients by Treatment Type",
       x = "Treatment Type",
       y = "Count")

ggplot(data, aes(x = stage, fill = stage)) +
  geom_bar() +
  labs(title = "Counts of Patients by Cancer Stage",
       x = "Cancer Stage",
       y = "Count")

ggplot(data, aes(x = gender, fill = gender)) +
  geom_bar() +
  labs(title = "Counts of Patients by Gender",
       x = "Gender",
       y = "Count")

names(data)

ggplot(data, aes(x = smoking_history, fill = smoking_history)) +
  geom_bar() +
  labs(title = "Counts of Patients by Smoking History",
       x = "Smoking History Categories",
       y = "Count")

ggplot(data, aes(x = tumor_location, fill = tumor_location)) +
  geom_bar() +
  labs(title = "Counts of Patients by Tumor Location",
       x = "Tumor Location",
       y = "Count")

ggplot(data, aes(x = ethnicity, fill = ethnicity)) +
  geom_bar() +
  labs(title = "Counts of Patients by Ethnicity",
       x = "Ethnicity",
       y = "Count")

ggplot(data, aes(x = ethnicity, fill = ethnicity)) +
  geom_bar() +
  labs(title = "Counts of Patients by Ethnicity",
       x = "Ethnicity",
       y = "Count")

ggplot(data, aes(x = insurance_type, fill = insurance_type)) +
  geom_bar() +
  labs(title = "Counts of Patients by Insurance Type",
       x = "Insurance Type",
       y = "Count")


ggplot(data, aes(x = insurance_type, fill = insurance_type)) +
  geom_bar() +
  labs(title = "Counts of Patients by Insurance Type",
       x = "Insurance Type",
       y = "Count")


ggplot(data, aes(x = family_history, fill = family_history)) +
  geom_bar() +
  labs(title = "Counts of Patients by Family History",
       x = "Family History",
       y = "Count")

ggplot(data, aes(x = comorbidity_diabetes, fill = comorbidity_diabetes)) +
  geom_bar() +
  labs(title = "Counts of Patients with Diabetes",
       x = "Diabetes (yes or no)",
       y = "Count")

ggplot(data, aes(x = comorbidity_hypertension, fill = comorbidity_hypertension)) +
  geom_bar() +
  labs(title = "Counts of Patients with Hypertension",
       x = "Hypertension (yes or no)",
       y = "Count")

ggplot(data, aes(x = comorbidity_heart_disease, fill = comorbidity_heart_disease)) +
  geom_bar() +
  labs(title = "Counts of Patients with Heart Disease",
       x = "Heart Disease (yes or no)",
       y = "Count")
ggplot(data, aes(x = comorbidity_chronic_lung_disease, fill =  comorbidity_chronic_lung_disease)) +
  geom_bar() +
  labs(title = "Counts of Patients with Chronic Lung Disease",
       x = "Chronic Lung Disease (yes or no)",
       y = "Count")

ggplot(data, aes(x = comorbidity_kidney_disease, fill = comorbidity_kidney_disease)) +
  geom_bar() +
  labs(title = "Counts of Patients with Kidney Disease",
       x = "Kidney Disease (yes or no)",
       y = "Count")

ggplot(data, aes(x = comorbidity_autoimmune_disease, fill = comorbidity_autoimmune_disease)) +
  geom_bar() +
  labs(title = "Counts of Patients with Autoimmune Disease",
       x = "Autoimmune Disease (yes or no)",
       y = "Count")

ggplot(data, aes(x = comorbidity_other, fill = comorbidity_other)) +
  geom_bar() +
  labs(title = "Counts of Patients with other Diseases",
       x = "Other Diseases (yes or no)",
       y = "Count")
```

## Character to Num Value

```{r}
#data = mutate(data, comorbidity_diabetes = ifelse(comorbidity_diabetes == 'Yes', 1, 0), 
             # comorbidity_hypertension = ifelse(comorbidity_hypertension == 'Yes', 1, 0),
             # family_history = ifelse(family_history == 'Yes', 1, 0), 
             # comorbidity_heart_disease = ifelse(comorbidity_heart_disease == 'Yes', 1, 0),
            #  comorbidity_chronic_lung_disease = ifelse(comorbidity_chronic_lung_disease == 'Yes', 1, 0),
             # comorbidity_kidney_disease = ifelse(comorbidity_kidney_disease == 'Yes', 1, 0),
              #comorbidity_autoimmune_disease = ifelse(comorbidity_autoimmune_disease == 'Yes', 1, 0),
              #comorbidity_other = ifelse(comorbidity_other == 'Yes', 1, 0))
```

## Heatmap To assess Correlation

```{r}
#head(data$stage). ### Previous Code  -- Jumbled all the stages 
#data$stage <- factor(data$stage, levels = unique(data$stage))

desired_order <- c("Stage I", "Stage II", "Stage III", "Stage IV")
data$stage <- factor(data$stage, levels = desired_order)
```

```{r}


#data$stage <- factor(data$stage, levels = unique(data$stage))

data$comorbidity_diabetes <- factor(data$comorbidity_diabetes, levels = unique(data$comorbidity_diabetes))


ggplot(data, aes(x = stage, y = comorbidity_diabetes, fill = survival_months)) + 
  geom_tile(color = "black", width = 1, height = 1) +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels if needed
```

```{r}

```

```{r}

#data$stage <- factor(data$stage, levels = unique(data$stage))

data$comorbidity_hypertension <- factor(data$comorbidity_diabetes, levels = unique(data$comorbidity_hypertension))


ggplot(data, aes(x = stage, y = comorbidity_hypertension, fill = survival_months)) + 
  geom_tile(color = "black", width = 1, height = 1) +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels if needed
```

```{r}

insurance_desired_levels = c("Other", "Private", "Medicare", "Medicaid")

data$insurance_type <- factor(data$insurance_type, levels = insurance_desired_levels)


ggplot(data, aes(x = stage, y = insurance_type, fill = survival_months)) + 
  geom_tile(color = "black", width = 1, height = 1) +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
